---
- hosts: all
  become: yes

  vars:
    env_name: test

  tasks:

    - name: copiar frontData
      command: rsync -a /var/www/default/frontData/ /var/www/{{ env_name }}-frontData/

    - name: copiar serviceData
      command: rsync -a /var/www/default/serviceData/ /var/www/{{ env_name }}-serviceData/