---
- hosts: all
  become: yes

  vars:
    db_name: "{{ env_name | replace('-', '_') }}_data_city"

  tasks:

    - name: criar diretório frontData
      file:
        path: "/var/www/{{ env_name }}-frontData"
        state: directory

    - name: criar diretório serviceData
      file:
        path: "/var/www/{{ env_name }}-serviceData"
        state: directory

    - name: copiar frontData
      synchronize:
        src: /var/www/default/frontData/
        dest: "/var/www/{{ env_name }}-frontData/"
        recursive: yes
      delegate_to: "{{ inventory_hostname }}"

    - name: copiar serviceData
      synchronize:
        src: /var/www/default/serviceData/
        dest: "/var/www/{{ env_name }}-serviceData/"
        recursive: yes
      delegate_to: "{{ inventory_hostname }}"

    - name: gerar arquivo .env
      template:
        src: templates/env.j2
        dest: "/var/www/{{ env_name }}-serviceData/.env"

    - name: criar banco mysql
      command: >
        mysql -u root -p540298cb
        -e "CREATE DATABASE {{ db_name }};"

    - name: limpar cache laravel
      command: php artisan optimize:clear
      args:
        chdir: "/var/www/{{ env_name }}-serviceData"

    - name: rodar migrate
      command: php artisan migrate --force
      args:
        chdir: "/var/www/{{ env_name }}-serviceData"
